### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by sfhacker** [agentcontest/massim_2020#15]
Ciao.

We are (brand) new to this contest so .... bear with us!
We have downloaded the latest binaries and started the server:

                   java -jar server-2020-1.0-jar-with-dependencies.jar --monitor

Our conf file looks like this:

{
  "scenario": "assemble2020",
  "host": "127.0.0.1",
  "port": 12300,
  "scheduling": false,
  "only-once": true,
  "timeout": 3000,
  "times": false,
  "notifications": false,
  "queued": false,
  "entities": [
    {
      "name":  "connectionA1",
      "username":  "agentA1",
      "password":  "abc",
      "print-iilang": false,
      "print-json": true
    },
{
      "name":  "connectionA1",
      "username":  "agentA2",
      "password":  "xyz",
      "print-iilang": false,
      "print-json": true
    }
  ]
}

When trying to connect and authenticate, we are unable to do so.

![image](https://user-images.githubusercontent.com/25817529/81068448-bca86000-8f23-11ea-9ff1-f6647bfb77b2.png)

We are not sure how the server should be set up and test it. There is nothing useful under the logs folder.

Any pointers/advice is appreciated.

Thanks in advance.

**Comment by t-ah** [comment]
Welcome aboard!

So it looks like the server is set up correctly and you want to connect to the server using [eismassim](https://github.com/agentcontest/massim_2020/blob/master/docs/eismassim.md). Your agentA1 may be authenticating successfully. At least its message can be read and processed by the server. If the credentials were wrong, it would look like this:
<img width="669" alt="grafik" src="https://user-images.githubusercontent.com/6231672/81071865-949a0c00-8ee5-11ea-9974-9bb52c49f894.png">
while successful attempts were not logged. Maybe this is confusing, so I added a log message in the last commit.

Maybe there is a problem because you are using the same name (connectionA1) twice in your eismassim config.

For setting up the server, there is a bit on the configuration [here](https://github.com/agentcontest/massim_2020/blob/master/docs/server.md#configuration). For authentication, probably the [teams block](https://github.com/agentcontest/massim_2020/blob/master/docs/server.md#teams-block) is most relevant.
The [SampleConfig](https://github.com/agentcontest/massim_2020/blob/master/server/conf/SampleConfig.json) should run as it is out of the box. It configures 50 accounts for team A and B each.

There is also a sample [eismassim config](https://github.com/agentcontest/massim_2020/blob/master/eismassim/conf/eismassimconfig.json) that corresponds to the server configuration SampleConfig and if you are using the very basic javaagents, there is also a [corresponding configuration](https://github.com/agentcontest/massim_2020/tree/master/javaagents/conf/BasicAgents) for these that uses the same eismassim configuration.

If you do not want to use eismassim to connect to the server, you could also just build and send the json messages yourself according to the [protocol](https://github.com/agentcontest/massim_2020/blob/master/docs/protocol.md).
